config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    sessions: 'users/sessions'
    }

  root 'items#index'

  get 'users/:id/logout', to: 'users#show', as: :user_logout
  get 'users/:id/profile', to: 'users#edit', as: :user_edit
  get 'users/:id/card', to: 'users#edit', as: :user_card_edit
  get 'users/profile', to: 'users#profile', as: :user_profile

  resources :users, only: [:new, :show, :edit, :update, :create_address] do
    resources :user_addresses, only: [:new, :create, :edit, :update]
  end


  resources :items do
    resources :purchase, only: [:index] do
      collection do
        get 'index', to: 'purchase#index'
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
    collection do
      get 'search'
      get 'get_child_categories', defaults: { format: 'json' }
      get 'get_grandchild_categories', defaults: { format: 'json' }
    end
  end

  resources :item_comments, only: :create
  resources :categories, only: [:index, :show]
  resources :brands, only: [:index, :show]
  resources :user_reviewes, only: [:index, :create]


  resources :signup, only: [:index, :create] do

    collection do
      get 'index'
      get 'registration'
      get 'sms_confirmation'
      get 'sms_confirmed'
      get 'delivery_address'
      get 'card'
      get 'done'
    end
  end

  get 'mypage', to: 'mypage/mypage#index', as: :mypage_top

  namespace :mypage do
    get 'listings/listing', to: 'listings#index', as: :listings_listing
    get 'profile', to: 'profile#edit', as: :edit_profile
    patch 'profile', to: 'profile#update', as: :update_profile
    resources :card, only: [:new, :show, :destroy]
    post 'card/new', to: 'card#pay', as: :pay_card
    get 'identification', to: 'identification#edit', as: :edit_identification
    patch 'identification', to: 'identification#update', as: :update_identification
    get 'logout', to: 'logout#logout', as: :mypage_logout
  end

  get '*path', to: 'errors#not_found'

end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    render :index, layout: "free-layout"
  end

  def registration
    @user = User.new
    render :registration, layout: "free-layout"
  end


  def sms_confirmation
    session[:nickname] = user_params[:nickname]
    session[:email] = user_params[:email]
    session[:password] = user_params[:password]
    session[:password_confirmation] = user_params[:password_confirmation]
    session[:kan_familyname] = user_params[:kan_familyname]
    session[:kan_firstname] = user_params[:kan_firstname]
    session[:kana_familyname] = user_params[:kana_familyname]
    session[:kana_firstname] = user_params[:kana_firstname]
    session[:birth_day] = user_params[:birth_day]
    @user = User.new
    render :sms_confirmation, layout: "free-layout"
  end

  def sms_confirmed
    session[:phone_number] = user_params[:phone_number]
    @user = User.new
    render :sms_confirmed, layout: "free-layout"
  end


  def delivery_address
    @user = User.new
    render :delivery_address, layout: "free-layout"
  end

  def card
    session[:postal_code] = user_params[:postal_code]
    session[:region] = user_params[:region]
    session[:city] = user_params[:city]
    session[:block] = user_params[:block]
    session[:buildings] = user_params[:buildings]
    session[:address_phone_number] = user_params[:address_phone_number]
    @user = User.new
    render :card, layout: "free-layout"
  end

  def create
    @user = User.new(
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      kan_familyname: session[:kan_familyname],
      kan_firstname: session[:kan_firstname],
      kana_familyname: session[:kana_familyname],
      kana_firstname: session[:kana_firstname],
      birth_day: session[:birth_day],
      phone_number: session[:phone_number],
      postal_code: session[:postal_code],
      region: session[:region],
      city: session[:city],
      block: session[:block],
      buildings: session[:buildings],
      address_phone_number: session[:address_phone_number]
    )
    if @user.save
      session[:id] = @user.id
      redirect_to done_signup_index_path
    else
      render '/signup/registration', layout: "free-layout"
    end
  end

  def done
    sign_in User.find(session[:id]) unless user_signed_in?
    render :done, layout: "free-layout"
  end

  private

    def user_params
      params.require(:user).permit(
        :nickname,
        :email,
        :password,
        :password_confirmation,
        :kan_familyname,
        :kan_firstname,
        :kana_familyname,
        :kana_firstname,
        :birth_day,
        :phone_number,
        :postal_code,
        :region,
        :city,
        :block,
        :buildings,
        :address_phone_number
        )
    end

end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/signup/card.html.haml
= render 'layouts/register-header5'
%main.new-user-main
  %section.new-user-contents
    %h2.new-user-input
      支払い方法

    = form_with(local: true, url: "/signup", method: :post) do |f|
      .contents__main
        .form-content.form-group.margin__top-40px
          .form-group
            = f.label :card_number, "カード番号"
            %span.form-require 必須
            = f.text_field :card_number, placeholder: "半角数字のみ", class: "form-group__input"
          %ul.signup-card-list.margin__top-8px
            %li
              = image_tag 'registration/visa.svg', size: '49x20'
            %li
              = image_tag 'registration/master.svg', size: '34x20'
            %li
              = image_tag 'registration/saison.svg', size: '30x20'
            %li
              = image_tag 'registration/jcb.svg', size: '32x20'
            %li
              = image_tag 'registration/american.svg', size: '21x20'
            %li
              = image_tag 'registration/diners.svg', size: '32x20'
            %li
              = image_tag 'registration/discover.svg', size: '32x20'

          .form-group
            = f.label :card, "有効期限"
            %span.form-require 必須
            %br
            .birthday-form
              .position-relative
                = f.select :card, [["01", "01"], ["02", "02"], ["03", "03"], ["04", "04"], ["05", "05"], ["06", "06"], ["07", "07"], ["08", "08"], ["09", "09"], ["10", "10"], ["11", "11"], ["12", "12"]], prompt: "--", class: "select-default"
                .fa.fa-chevron-down.form-icon-position__normal
                .contents__text.margin__side-2px.margin__right-8px
                  月
              .position-relative
                = f.select :card, [["19", "19"], ["20", "20"],["21", "21"], ["22", "22"],["23", "23"], ["24", "24"],["25", "25"], ["26", "26"],["27", "27"], ["28", "28"],["29", "29"]], prompt: "--", class: "select-default"
                .fa.fa-chevron-down.form-icon-position__normal
                .contents__text.margin__side-2px.margin__right-8px
                  年

          .form-group.margin__top-32px
            = f.label :security_code, "セキュリティコード"
            %span.form-require 必須
            = f.text_field :security_code, placeholder: "カード背面4桁もしくは3桁の番号", class: "form-group__input"
          .personal-register.margin__top-8px
            %p
              .form-question
                ?
              = link_to("カード裏面の番号とは?", "#", {class: "blue-color-link"})
          = f.submit "次へ進む", class: "next-btn btn square-btn contents__text margin__top-24px"
= render 'layouts/register-footer'

app/views/signup/delivery_address.html.haml
= render 'layouts/register-header4'
%main.new-user-main
  %section.new-user-contents
    %h2.new-user-input
      発送元・お届け先住所入力

    =form_with(model: @user, local: true, url: card_signup_index_path, method: :get) do |f|
      .contents__main
        .form-content.form-group.margin__top-40px
          .form-group
            = f.label :kanji, "お名前"
            %span.form-require 必須
            = f.text_field :kan_familyname, placeholder: "例)山田", class: "form-group__input", value: "#{session[:kan_familyname]}"
            = f.text_field :kan_firstname, placeholder: "例)彩", class: "form-group__input", value: "#{session[:kan_firstname]}"

          .form-group.margin__top-32px
            = f.label :kana, "お名前カナ"
            %span.form-require 必須
            = f.text_field :kana_familyname, placeholder: "例)ヤマダ", class: "form-group__input", value: "#{session[:kana_familyname]}"
            = f.text_field :kana_firstname, placeholder: "例)アヤ", class: "form-group__input", value: "#{session[:kana_firstname]}"

          .form-group.margin__top-32px
            = f.label :postal_code, "郵便番号"
            %span.form-require 必須
            = f.text_field :postal_code, placeholder: "例)123-4567", class: "form-group__input"

          .form-group.margin__top-32px
            = f.label :region, "都道府県"
            %span.form-require 必須
          .position-relative
            .fa.fa-chevron-down.form-icon-position__prefecture
            = f.collection_select(:region, Prefecture.all, :id, :name, {prompt: "--"}, {class: 'form-group__input'})

          .form-group.margin__top-32px
            = f.label :city, "市区町村"
            %span.form-require 必須
            = f.text_field :city, placeholder: "例)横浜市緑区", class: "form-group__input"

          .form-group.margin__top-32px
            = f.label :block, "番地"
            %span.form-require 必須
            = f.text_field :block, placeholder: "例)青山1-1-1", class: "form-group__input"

          .form-group.margin__top-32px
            = f.label :buildings, "建物名"
            %span.form-require.form-require__optional 任意
            = f.text_field :buildings, placeholder: "例)柳ビル103", class: "form-group__input"

          .form-group.margin__top-32px
            = f.label :address_phone_number, "電話"
            %span.form-require.form-require__optional 任意
            = f.text_field :address_phone_number, placeholder: "例)09012345678", class: "form-group__input"

          = f.submit "次へ進む", class: "next-btn btn square-btn contents__text margin__top-32px margin__bottom-60px"
= render 'layouts/register-footer'

app/views/signup/done.html.haml
= render 'layouts/register-header6'
%main.new-user-main
  %section.new-user-contents
    %h2.new-user-input
      会員登録完了
      .contents__main
        .form-content.form-group.margin__top-40px
          .form-group
            .rule-text.font__size-16px
              ありがとうございます。
              %br
              会員登録が完了しました。
          = link_to "メルカリをはじめる", root_path, class: "next-btn btn btn__start square-btn contents__text margin__top-32px margin__bottom-24px"
    = link_to "#" do
      = image_tag 'registration/bunner.jpg', class: "registration-bunner"
= render 'layouts/register-footer'

app/views/signup/index.html.haml
= render 'layouts/register-header'

.register_container

  %main.register
    %section.contents
      %h2.contents__new
        新規会員登録
      .contents__main.main
        .main__list
          = link_to "メールアドレスで登録する", registration_signup_index_path, class: "btn-mail btn"
        .main__list
          = link_to "Facebookで登録する", user_facebook_omniauth_authorize_path, method: :post, class: "btn-facebook btn"
        .main__list
          = link_to "Googleで登録する", user_google_oauth2_omniauth_authorize_path, method: :post, class: "btn-google btn"
= render 'layouts/register-footer'

app/views/signup/registration.html.haml
= render 'layouts/register-header2'
%main.new-user-main

  - if @user.errors.any?
    %h2
      = @user.errors.count
      件のエラーがあります。
    %ul
      - @user.errors.full_messages.each do |msg|
        %li
          = msg

  %section.new-user-contents
    %h2.new-user-input
      会員情報入力
    = form_for(@user, url: sms_confirmation_signup_index_path, class: "form-wrap", method: :get) do |f|
      .contents__main
        .form-content.form-group

          .form-group
            = f.label :nickname, "ニックネーム"
            %span.form-require 必須
            = f.text_field :nickname, placeholder: "例)メルカリ太郎", class: "form-group__input"

          .form-group
            = f.label :email, "メールアドレス"
            %span.form-require 必須
            = f.email_field :email, placeholder: "PC・携帯どちらでも可", class: "form-group__input reg-email"

          - if @user.email.blank?
            .form-group.reg-pass
              = f.label :password, "パスワード"
              %span.form-require 必須
              = f.password_field :password, placeholder: "7文字以上", class: "form-group__input"

            .form-group.reg-pass-conf
              = f.label :password, "パスワード (確認)"
              %span.form-require 必須
              = f.password_field :password_confirmation, placeholder: "7文字以上", class: "form-group__input"

          - else
            .form-group.reg-pass{style: "display: none;"}
              = f.label :password, "パスワード"
              %span.form-require 必須
              = f.password_field :password, placeholder: "7文字以上", class: "form-group__input", value: "#{@user.password}"

            .form-group.reg-pass-conf{style: "display: none;"}
              = f.label :password, "パスワード (確認)"
              %span.form-require 必須
              = f.password_field :password_confirmation, placeholder: "7文字以上", class: "form-group__input", value: "#{@user.password_confirmation}"

          .form-group
            .text-left.l-character-sub-head.font__size-16px
              本人確認
            %p.contents__text
              安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。

          .form-group
            %div
              = f.label "お名前(全角)"
              %span.form-require 必須
            .form-name
              = f.text_field :kan_familyname, placeholder: "例)山田", class: "form-group__input name-left"
              = f.text_field :kan_firstname, placeholder: "例)彩", class: "form-group__input"

          .form-group
            %div
              = f.label "お名前カナ(全角)"
              %span.form-require 必須
            .form-name
              = f.text_field :kana_familyname, placeholder: "例)ヤマダ", class: "form-group__input name-left"
              = f.text_field :kana_firstname, placeholder: "例)アヤ", class: "form-group__input"

          .form-group
            = f.label :birth_day, "生年月日"
            %span.form-require 必須
            %br

            .birthday-form
              .birthday-form__year
                = f.select :birth_day, options_for_select(1900..2019), prompt: "--", class: "select-default"
                .fa.fa-chevron-down.form-icon-position__normal
                .contents__text.margin__side-2px
                  年
              .birthday-form__month
                = f.select :birth_day, options_for_select(1..12), prompt: "--"
                .fa.fa-chevron-down.form-icon-position__normal
                .contents__text.margin__side-2px
                  月
              .birthday-form__day
                = f.select :birth_day, options_for_select(1..31), prompt: "--"
                .fa.fa-chevron-down.form-icon-position__normal
                .contents__text.margin__side-2px
                  日

          %p.form-info-text.contents__text
            * 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。

          .form-group
            %p.rule-text
              「次へ進む」のボタンを押すことにより、
              = link_to("利用規約", "#", {class: "blue-color-link"})
              に同意したものとみなします

            = f.submit "次へ進む", class: "next-btn btn square-btn contents__text"
            .form-group.personal-register.margin__top-24px
              %p
                = link_to("本人情報の登録について", "#", {class: "blue-color-link"})
                %i.fa.fa-chevron-right.blue-color-link
= render 'layouts/register-footer'

app/views/signup/sms_confirmation.html.haml
= render 'layouts/register-header3'
%main.new-user-main
  %section.new-user-contents
    %h2.new-user-input
      .h2
        電話番号の確認

    = form_for(:user, url: sms_confirmed_signup_index_path, class: "form-wrap", method: :get) do |f|
      .contents__main

        .form-content.form-group

          .form-group
            = f.label :phone_number, "携帯電話の番号"
            = f.text_field :phone_number, placeholder: "携帯電話の番号を入力", class: "form-group__input"
            %p.contents__text.margin__top-8px
              本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います。

            = f.submit "SMSを送信する", class: "next-btn btn square-btn contents__text margin__top-24px"

          .contents__text.margin__top-8px
            ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。

          .form-group.personal-register.margin__top-24px
            %p
              = link_to("電話番号の確認が必要な理由", "#", {class: "blue-color-link"})
              %i.fa.fa-chevron-right.blue-color-link.icon-thinner
= render 'layouts/register-footer'

app/views/signup/sms_confirmed.html.haml
= render 'layouts/register-header3'
%main.new-user-main
  %section.new-user-contents
    %h2.new-user-input
      .h2
        電話番号認証

    = form_for(:user, url: delivery_address_signup_index_path, class: "form-wrap", method: :get) do |f|
      .contents__main

        .form-content.form-group

          .form-group
            = f.label :confirmation, "認証番号"
            = f.text_field :nickname, placeholder: "認証番号を入力", class: "form-group__input"
            %p.contents__text.margin__top-8px
              SMSで届いた認証番号を入力してください

            = f.submit "認証して完了", class: "next-btn btn square-btn contents__text margin__top-24px"
      .contents__main

        .form-content.form-group

          .form-group
            .contents__subtitle
              30秒たっても認証番号が届かない方へ
            %p.contents__text.margin__top-8px
              電話で認証番号を聞くこともできます。

            = f.submit "電話で認証番号を聞く（通話無料）", class: "next-btn btn square-btn contents__text margin__top-24px"

      .contents__main

        .form-content.form-group

          .form-group
            .contents__subtitle
              認証番号を再送することもできます。もう一度電話番号を入力して下さい。
          = link_to("電話番号を再度入力する", "#", {class:"contents__text top-8px blue-color-link"})

          .form-group
            %p.rule-text
              ※SMSが届かない場合は
              = link_to("SMS受信設定", "#", {class: "blue-color-link"})
              を確認して、もう一度電話番号を入力してください。
= render 'layouts/register-footer'