config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    sessions: 'users/sessions'
    }

  root 'items#index'

  get 'users/:id/logout', to: 'users#show', as: :user_logout
  get 'users/:id/profile', to: 'users#edit', as: :user_edit
  get 'users/:id/card', to: 'users#edit', as: :user_card_edit
  get 'users/profile', to: 'users#profile', as: :user_profile

  resources :users, only: [:new, :show, :edit, :update, :create_address] do
    resources :user_addresses, only: [:new, :create, :edit, :update]
  end


  resources :items do
    resources :purchase, only: [:index] do
      collection do
        get 'index', to: 'purchase#index'
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
    collection do
      get 'search'
      get 'get_child_categories', defaults: { format: 'json' }
      get 'get_grandchild_categories', defaults: { format: 'json' }
    end
  end

  resources :item_comments, only: :create
  resources :categories, only: [:index, :show]
  resources :brands, only: [:index, :show]
  resources :user_reviewes, only: [:index, :create]


  resources :signup, only: [:index, :create] do

    collection do
      get 'index'
      get 'registration'
      get 'sms_confirmation'
      get 'sms_confirmed'
      get 'delivery_address'
      get 'card'
      get 'done'
    end
  end

  get 'mypage', to: 'mypage/mypage#index', as: :mypage_top

  namespace :mypage do
    get 'listings/listing', to: 'listings#index', as: :listings_listing
    get 'profile', to: 'profile#edit', as: :edit_profile
    patch 'profile', to: 'profile#update', as: :update_profile
    resources :card, only: [:new, :show, :destroy]
    post 'card/new', to: 'card#pay', as: :pay_card
    get 'identification', to: 'identification#edit', as: :edit_identification
    patch 'identification', to: 'identification#update', as: :update_identification
    get 'logout', to: 'logout#logout', as: :mypage_logout
  end

  get '*path', to: 'errors#not_found'

end

app/controllers/purchase_controller.rb
class PurchaseController < ApplicationController

  before_action :set_item, only: [:index, :pay, :done]
  before_action :set_card, only: [:pay, :done]

  def index
    @region = Region.all

    return redirect_to user_session_path unless user_signed_in?

    if @item.user_id == current_user.id
      redirect_to root_path
      return
    elsif @item.sold_condition == 3
      redirect_to item_path(@item)
      return
    end
    
    set_card
    if @card.blank?
      redirect_to controller: "mypage/card", action: "new"
    else
      set_payjp
      render layout: "register-layout"
    end
  end

  def pay
    redirect_to root_path and return if @item.user_id == current_user.id
    Payjp::api_key = Rails.application.credentials.PAYJP_PRIVATE_KEY
    Payjp::Charge.create(
      :amount => @item.price,
      :customer => @card.customer_id,
      :currency => 'jpy'
    )
    redirect_to done_item_purchase_index_path(@item)
  end

  def done
    @region = Region.all
    @item.update_attribute(:sold_condition, 3)
    set_payjp
    render layout: "register-layout"
  end

  private

  def set_item
    @item = Item.find(params[:item_id])
  end

  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end

  def set_payjp
    Payjp.api_key = Rails.application.credentials.PAYJP_PRIVATE_KEY
    customer = Payjp::Customer.retrieve(@card.customer_id)
    @default_card_information = customer.cards.retrieve(@card.card_id)
  end
end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/views/purchase/done.html.haml
%main.pur
  %section.pur-contents
    %h2.pur-title 購入が完了しました
    %section.pur-item
      .pur-item__inner
        .pur-item__inner__img-box
          = image_tag @item.images.first.image.url, class: "pur-item__inner__img-box__img"
        %p.pur-item__inner__text
          = @item.name
        = form_with url: pay_item_purchase_index_path(@item.id), method: :post, local: true, class: "pur-form" do |f|
          %p.pur-form__item-price
            ¥
            = @item.price.to_s(:delimited, delimiter: ',')
            %span.pur-form__item-price__shipping-fee
              送料込み

    %section.pur-delivery
      .pur-delivery__inner
        %h3.pur-delivery__inner__title 配送先
        %address.pur-delivery__inner__address
          = current_user.postal_code
          %br/
          = @region.find(current_user.region).region
          = current_user.city
          = current_user.block
          = current_user.buildings
          %br/
          = current_user.nickname
        = link_to "#", class: "pur-link" do
          = fa_icon 'angle-right', class: 'pur-link__icon'
    %section.pur-card
      .pur-card__inner
        %h3.pur-card__inner__text 支払い方法
        %p.pur-card__inner__card-info
          = "**** **** **** " + @default_card_information.last4
          %br/
          - exp_month = @default_card_information.exp_month.to_s
          - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
          = exp_month + " / " + exp_year
        %figure.card-icon
          = image_tag asset_path('purchase/master-card.svg'), size: '34x20'
        = link_to "#", class: "pur-link" do
          = fa_icon 'angle-right', class: 'pur-link__icon'

app/views/purchase/index.html.haml
%main.pur
  %section.pur-contents
    %h2.pur-title 購入内容の確認
    %section.pur-item
      .pur-item__inner
        .pur-item__inner__img-box
          = image_tag @item.images.first.image.url, class: "pur-item__inner__img-box__img"
        %p.pur-item__inner__text
          = @item.name
        = form_with url: pay_item_purchase_index_path(@item.id), method: :post, local: true, class: "pur-form" do |f|
          %p.pur-form__item-price 
            ¥
            = @item.price.to_s(:delimited, delimiter: ',')
            %span.pur-form__item-price__shipping-fee 
              送料込み
          %ul.pur-form__point
            %li.pur-form__point__box
              .pur-form__point__box__text 
                ポイントはありません
          %ul.pur-form__purchase-price
            %li.pur-form__purchase-price__box
              .pur-form__purchase-price__box__text 
                支払い金額
              .pur-form__purchase-price__box__price
                %span.pur-form__purchase-price__box__price__text
                  ¥
                  = @item.price.to_s(:delimited, delimiter: ',')
            = f.submit "購入する", class: "btn-red pur"

    %section.pur-delivery
      .pur-delivery__inner
        %h3.pur-delivery__inner__title 配送先
        %address.pur-delivery__inner__address
          = current_user.postal_code
          %br/
          = @region.find(current_user.region).region
          = current_user.city
          = current_user.block
          = current_user.buildings
          %br/
          = current_user.nickname
        = link_to "#", class: "pur-link" do
          %span.pur-link__text 変更する
          = fa_icon 'angle-right', class: 'pur-link__icon'
    %section.pur-card
      .pur-card__inner
        %h3.pur-card__inner__text 支払い方法
        %p.pur-card__inner__card-info
          = "**** **** **** " + @default_card_information.last4
          %br/
          - exp_month = @default_card_information.exp_month.to_s
          - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
          = exp_month + " / " + exp_year
        %figure.card-icon
          = image_tag asset_path('purchase/master-card.svg'), size: '34x20'
        = link_to "#", class: "pur-link" do
          %span.pur-link__text 変更する
          = fa_icon 'angle-right', class: 'pur-link__icon'