config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    sessions: 'users/sessions'
    }

  root 'items#index'

  get 'users/:id/logout', to: 'users#show', as: :user_logout
  get 'users/:id/profile', to: 'users#edit', as: :user_edit
  get 'users/:id/card', to: 'users#edit', as: :user_card_edit
  get 'users/profile', to: 'users#profile', as: :user_profile

  resources :users, only: [:new, :show, :edit, :update, :create_address] do
    resources :user_addresses, only: [:new, :create, :edit, :update]
  end


  resources :items do
    resources :purchase, only: [:index] do
      collection do
        get 'index', to: 'purchase#index'
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
    collection do
      get 'search'
      get 'get_child_categories', defaults: { format: 'json' }
      get 'get_grandchild_categories', defaults: { format: 'json' }
    end
  end

  resources :item_comments, only: :create
  resources :categories, only: [:index, :show]
  resources :brands, only: [:index, :show]
  resources :user_reviewes, only: [:index, :create]


  resources :signup, only: [:index, :create] do

    collection do
      get 'index'
      get 'registration'
      get 'sms_confirmation'
      get 'sms_confirmed'
      get 'delivery_address'
      get 'card'
      get 'done'
    end
  end

  get 'mypage', to: 'mypage/mypage#index', as: :mypage_top

  namespace :mypage do
    get 'listings/listing', to: 'listings#index', as: :listings_listing
    get 'profile', to: 'profile#edit', as: :edit_profile
    patch 'profile', to: 'profile#update', as: :update_profile
    resources :card, only: [:new, :show, :destroy]
    post 'card/new', to: 'card#pay', as: :pay_card
    get 'identification', to: 'identification#edit', as: :edit_identification
    patch 'identification', to: 'identification#update', as: :update_identification
    get 'logout', to: 'logout#logout', as: :mypage_logout
  end

  get '*path', to: 'errors#not_found'

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  has_many :sizes_categories
  has_many :sizes, through: :sizes_categories
  has_ancestry

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authenticate_user!
  require 'wikipedia'

  def index
    @categories = Category.all
    @parents = Category.roots
  end

  def show
    @category = Category.find(params[:id])
    @info = wiki(@category.name)
    if @category.is_root?
      parents = Category.find_by(id: @category.id).subtree
      @items = Item.where(category_id: parents).page(params[:page]).per(120).order("created_at DESC").includes(:images)
    elsif @category.has_parent? && @category.has_children?
      children = Category.find_by(id: @category.id).subtree
      @items = Item.where(category_id: children).page(params[:page]).per(120).order("created_at DESC").includes(:images)
    else
      @items = Item.where(category_id: @category.id).page(params[:page]).per(120).order("created_at DESC").includes(:images)
    end
  end

  private

  def wiki(category)
    Wikipedia.configure {
      domain 'ja.wikipedia.org'
      path 'w/api.php'
    }

    page = Wikipedia.find(category)
    return page.summary
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.haml
= render "layouts/breadcrumbs"
.visible-pc2
  .gray
    %h2 カテゴリー一覧
  .category-list-nav.slide-nav-prent.text-center.clearfix
    - @parents.each do |parent|
      = link_to "#category-#{parent.id}", class: "white category-root-category-link-name" do
        %div
          = parent.name
  .category-list-box
    - @parents.each do |parent|
      .category-list-individual-box.white
        %div{class: "category-list-individual-box-root-category-name", id: "category-#{parent.id}"}
          %h3
            = parent.name
        .category-list-individual-box-inner-box
          %p
            = link_to category_path(parent) do
              すべて
          - parent.children.each do |child|
            .category-list-individual-box-sub-category-name
              %h4
                = child.name
            .clearfix.category-list-individual-box-sub-sub-category-box
              .category-list-individual-box-sub-sub-category-name
                %p
                  = link_to category_path(child) do
                    すべて
              - child.children.each do |grand_child|
                .category-list-individual-box-sub-sub-category-name
                  %p
                    = link_to category_path(grand_child) do
                      = grand_child.name

app/views/categories/show.html.haml
%main.l-container
  .l-content
    %ul.parts-nav
  %section.items-box-container
    %h1.items-box-head
      = @category.name
      の商品一覧
    .items-box-content.category-brand-list
      - @items.each do |item|
        %section.search-item-box
          = link_to item_path(item) do
            %figure.search-item-box__image-box
              = image_tag item.images.first.image.url, class: "search-item-box__image-box__image"
            .search-item-box__text-box
              %h3.search-item-box__text-box__text
                = item.name
              .search-item-box__text-box__num
                .search-item-box__text-box__num__price
                  = "¥#{item.price.to_s(:delimited, delimiter: ',')}"
                - if item.likes ==! ""
                  .search-item-box__text-box__num__likes
                    %i.far.fa-heart
                    %span
                      = item.likes

    - if @info.present?
      .info-description
        .info-description-title
          %h3
            = @category.name
        .info-description-text
          %p
            = @info

        