config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    sessions: 'users/sessions'
    }

  root 'items#index'

  get 'users/:id/logout', to: 'users#show', as: :user_logout
  get 'users/:id/profile', to: 'users#edit', as: :user_edit
  get 'users/:id/card', to: 'users#edit', as: :user_card_edit
  get 'users/profile', to: 'users#profile', as: :user_profile

  resources :users, only: [:new, :show, :edit, :update, :create_address] do
    resources :user_addresses, only: [:new, :create, :edit, :update]
  end


  resources :items do
    resources :purchase, only: [:index] do
      collection do
        get 'index', to: 'purchase#index'
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
    collection do
      get 'search'
      get 'get_child_categories', defaults: { format: 'json' }
      get 'get_grandchild_categories', defaults: { format: 'json' }
    end
  end

  resources :item_comments, only: :create
  resources :categories, only: [:index, :show]
  resources :brands, only: [:index, :show]
  resources :user_reviewes, only: [:index, :create]


  resources :signup, only: [:index, :create] do

    collection do
      get 'index'
      get 'registration'
      get 'sms_confirmation'
      get 'sms_confirmed'
      get 'delivery_address'
      get 'card'
      get 'done'
    end
  end

  get 'mypage', to: 'mypage/mypage#index', as: :mypage_top

  namespace :mypage do
    get 'listings/listing', to: 'listings#index', as: :listings_listing
    get 'profile', to: 'profile#edit', as: :edit_profile
    patch 'profile', to: 'profile#update', as: :update_profile
    resources :card, only: [:new, :show, :destroy]
    post 'card/new', to: 'card#pay', as: :pay_card
    get 'identification', to: 'identification#edit', as: :edit_identification
    patch 'identification', to: 'identification#update', as: :update_identification
    get 'logout', to: 'logout#logout', as: :mypage_logout
  end

  get '*path', to: 'errors#not_found'

end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items
  belongs_to :item
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  has_many :sizes_categories
  has_many :sizes, through: :sizes_categories
  has_ancestry

end

app/models/delivery.rb
class Delivery < ApplicationRecord
end

app/models/delivery_pay.rb
class DeliveryPay < ActiveHash::Base
  self.data = [
    { id: 0, name: '送料込み（出品者負担）' }, { id: 1, name: '着払い（購入者負担）' }
  ]
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :item
  mount_uploader :image, ImageUploader
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :item_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :images, dependent: :destroy
  belongs_to :user
  belongs_to :category
  belongs_to :brand, optional: true
  belongs_to :region
  belongs_to :size, optional: true
  accepts_nested_attributes_for :images, allow_destroy: true

  validates :name,         presence: true,  length: { in: 1..40 }
  validates :description,  presence: true,  length: { in: 1..1000 }
  validates :price,        presence: true, numericality: {
              only_integer: true,
              greater_than_or_equal_to: 300,
              less_than_or_equal_to: 9999999,
              }
  validates :product_condition,
            :category_id,
            :region_id,
            :sold_condition,
            :user_id,
            :delivery_payee,
            :delivery_time,
            :delivery_method, presence: true
  validates :images, presence: true, length: { minimum: 1, maximum: 10 }

  def self.search(search)
    return Item.order(created_at: "DESC").limit(24) unless search
    Item.where(['name LIKE(?) OR description LIKE(?)', "%#{search}%", "%#{search}%"])
  end
end

app/models/item_comment.rb
class ItemComment < ApplicationRecord
  belongs_to :item
  belongs_to :user

  validates :comment, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}, {id: 48, name: '未定'}
  ]
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :items
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :sizes_categories
  has_many :category, through: :sizes_categories
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable,omniauth_providers: [:facebook, :google_oauth2]

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    if snscredential.present?
      user = User.where(id: snscredential.user_id).first
    else
      user = User.where(email: auth.info.email).first
      if user.present?
        SnsCredential.create(
          uid: uid,
          provider: provider,
          user_id: user.id
        )
      else
        password = Devise.friendly_token[0, 20]
        user = User.new(
          nickname: auth.info.name,
          email: auth.info.email,
          password: password,
          password_confirmation: password
        )
        SnsCredential.new(
          uid: uid,
          provider: provider
        )
      end
    end
    return user
  end

  has_many :items, dependent: :destroy
  has_many :user_reviews, dependent: :destroy
  has_many :item_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one :card
  has_one :user_address
  has_one :delivery_address

  validates :nickname,
            :email,
            :kan_familyname,
            :kan_firstname,
            :kana_familyname,
            :kana_firstname,
            :birth_day, 
            :phone_number,
            :region, 
            :city, 
            :block, presence: true

  validates :email, :phone_number, uniqueness: true
  validates :kan_familyname, :kan_firstname, format: { with: /\A[ぁ-んァ-ン一-龥]/ }
  validates :kana_familyname, :kana_firstname, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :phone_number, format: { with: /\A\d{10,11}\z/ }, length: { in: 10..11 }
  validates :address_phone_number, allow_nil: true, format: { with: /\A\d{10,11}\z/ }, length: { in: 10..11 }

  validates :password, :password_confirmation, allow_nil: true, presence: true, length: { minimum: 7 }
  validates :postal_code, format: {with: /\A[0-9]{3}-[0-9]{4}\z/}, presence: true
end

app/models/user_address.rb
class UserAddress < ApplicationRecord
  belongs_to :user

  validates :postal_code, length: { is: 7 }, format: { with: /\A\d{7}\z/ }
end

app/models/user_review.rb
class UserReview < ApplicationRecord
  belongs_to :user

  validates :rate, presence: true
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_breadcrumbs.html.haml
- case params.values_at :controller, :action

- when ['mypage/mypage', 'index']
  - breadcrumb :mypage

- when ['mypage/profile', 'edit']
  - breadcrumb :mypage_profile

- when ['mypage/card', 'new']
  - breadcrumb :mypage_card

- when ['mypage/identification', 'edit']
  - breadcrumb :mypage_identification

- when ['mypage/logout', 'logout']
  - breadcrumb :mypage_logout

- when ['mypage/listings', 'index']
  - breadcrumb :mypage_itemList

- when ['items', 'show']
  - breadcrumb :mypage_itemList_item

- when ['categories', 'index']
  - breadcrumb :categories

%nav.breadcrumbs
  = breadcrumbs class: "breadcrumbs__text", separator: " &nbsp;&nbsp;&#12297;&nbsp; "

app/views/layouts/_header.html.haml
%header
  .hd-contents
    .hd-top
      %h1.hd-top__logo
        = link_to root_path  do
          = image_tag 'header/mercari-logo.svg', size: '134x36', class: "hd-top__logo__link"
      = form_with url: search_items_path, method: :get, local: true, class: "hd-top__form" do |f|
        = f.text_field :search, class: 'hd-top__form__textarea',value: "#{params[:search]}", placeholder: '何かお探しですか？'
        = f.button type: 'submit', class: 'hd-top__form__icon', name: nil do
          = fa_icon 'search'
    .hd-btm
      %nav.hd-btm__left
        %ul.hd-left-list
          %li.hd-left-list__category
            %h2.hd-category-brand-components
              =link_to categories_path, class: "hd-category-brand-components__link" do
                = fa_icon 'list-ul', class: 'hd-category-brand-components__link__logo'
                %span.hd-category-brand-components__link__text カテゴリーから探す
          %li.hd-left-list__brand
            %h2.hd-category-brand-components
              =link_to '', class: "hd-category-brand-components__link" do
                = fa_icon 'tags', class: 'hd-category-brand-components__link__logo'
                %span.hd-category-brand-components__link__text ブランドから探す
      .hd-btm__right
        - if user_signed_in?
          %ul.hd-right-list
            %li.hd-right-list__likelist
              =link_to '', class: "hd-likelist-link" do
                %i.far.fa-heart.hd-likelist-link__logo
                %span.hd-likelist-link__text いいね!一覧
            %li.hd-right-list__news
              =link_to '', class: "hd-news-link" do
                %i.far.fa-bell.hd-news-link__logo
                %span.hd-news-link__text お知らせ
              %ul
            %li.hd-right-list__todolist
              =link_to '', class: "hd-todolist-link" do
                = fa_icon 'check', class: 'hd-todolist-link__logo'
                %span.hd-todolist-link__text やることリスト
              %ul
            %li.hd-right-list__mypage
              =link_to mypage_top_path, class: "hd-right-list__mypage__link" do
                %figure.hd-right-list__mypage__link__image
                  %div.hd-right-list__mypage__link__image__div
                    = image_tag 'header/userimage_if_noimage.png', size:'32x32', class: 'mypage-image'
                %span.hd-right-list__mypage__link__text マイページ
        - else
          %ul.hd-right-login
            %li
              = link_to "新規会員登録", signup_index_path, class: "hd-right-login__sign-in-btn"
            %li
              = link_to "ログイン", new_user_session_path, class: "hd-right-login__log-in-btn"

app/views/layouts/_item-show-not-user.html.haml
%section.is-box
  %h1.is-name
    = @item.name
  .is-main
    .is-photo
      .is-photo__portion
        .is-photo__up
          = image_tag @item.images.first.image.url, class:"change-image"
          .is-photo__down
            - if @item.sold_condition == 3
              .sold-tag
                %div SOLD
        .is-photo__down__portion
          .owl-dots
            - @images.each do |image|
              .owl-dot
                = image_tag image.image.url
    %table.is-detail-table
      %tbody
        %tr.is-tables
          %th 出品者
          %td
            = link_to "#" do
              = @item.user.nickname
            %div
              .is-user-ratings
                %i.fas.fa-laugh-squint.icon__good
                %span 8
              .is-user-ratings
                %i.fas.fa-meh.icon__normal
                %span 1
              .is-user-ratings
                %i.fas.fa-dizzy.icon__bad
                %span 0
        %tr.is-tables
          %th カテゴリー
          %td
            .blue-color-link
              = link_to "/categories/#{@parent_category.id}" do
                = @parent_category.name
                %br
              %i.fa.fa-chevron-right
              = link_to "/categories/#{@child_category.id}" do
                = @child_category.name
                %br
              %i.fa.fa-chevron-right
              = link_to "/categories/#{@item.category.id}" do
                = @item.category.name
        %tr.is-tables
          %th ブランド
          %td
            = link_to "#" do
              - if @item.brand.present?
                = @item.brand.name
              - else
        %tr.is-tables
          %th 商品の状態
          %td
            - case @item.sold_condition
              - when 1 then
                新品、未使用
              - when 2 then
                未使用に近い
              - when 3 then
                目立った傷や汚れなし
              - when 4 then
                やや傷や汚れあり
              - when 5 then
                傷や汚れあり
              - when 6 then
                全体的に状態が悪い
        %tr.is-tables
          %th 配送料の負担
          %td
            - case @item.delivery_payee
              - when 1 then
                送料込み(出品者負担)
              - when 2 then
                着払い(購入者負担)
        %tr.is-tables
          %th 配送の方法
          %td
            - case @item.delivery_method
              - when 1 then
                未定
              - when 2 then
                らくらくメルカリ便
              - when 3 then
                ゆうメール
              - when 4 then
                レターパック普通郵便（定形、定形外）
              - when 5 then
                クロネコヤマト
              - when 6 then
                ゆうパック
              - when 7 then
                クリックポスト
              - when 8 then
                ゆうパケット
              - when 9 then
                徒歩
        %tr.is-tables
          %th 配送元地域
          %td
            = link_to "#" do
              = @item.region.region
        %tr.is-tables
          %th 配送日の目安
          %td
            - case @item.delivery_time
              - when 1 then
                1~2日で発送
              - when 2 then
                2~3日で発送
              - when 3 then
                4~7日で発送
              - when 4 then
                今年中に発送
              - when 5 then
                発送しない
  .is-price-box.text-center
    %span.is-price ¥#{@item.price.to_s(:delimited, delimiter: ',')}
    %span.is-tax (税込)
    %span.is-shipping-fee 送料込み
  - if @item.sold_condition == 3
    %button.btn-buy-not-gray 売り切れました
  - else
    = link_to "購入画面に進む", item_purchase_index_path(@item), class: "is-buy-btn"
  .is-message
    %p.is-description-inner
      = @item.description
  .is-button-container
    .is-button-left
      %button{class: "is-button-like", type: "button"}
        %span
          %i.far.fa-heart
            いいね!
            = @item.likes.length
      %a.is-button_is-button-report
        %span
          %i.far.fa-flag
          不適切な商品の報告
    .is-button-right
      = link_to "#" do
        %i.fa.fa-lock.blue-color-link.font__size-14px
          あんしん・あんぜんへの取り組み
.is-nav.blue-color-link.font__size-14px
  %li.is-nav__prev
    = link_to "#" do
      %i.fa.fa-chevron-left
        通勤をより過酷に！加重Macbook Air 50kg
  %li.is-nav__next
    = link_to "#" do
      [カフェイン1000g配合]自作エナジードリンク
      %i.fa.fa-chevron-right
.is-sns-box
  %ul.is-sns-box__items
    = image_tag 'item/sns.png', size: '160x50'
.is-in-user
  %section.is-container
    %h2.is-items-head
      = link_to "#", class:"blue-color-link" do
        = @item.user.nickname
        さんのその他の出品
      .is-content
        - @item.user.items.each do |item|
          - unless @item == item
            %section.is-content__card
              = link_to item_path(item) do
                .is-content__photo
                  = image_tag item.images.first.image.url
                .is-content__body
                  .is-content__name.in-item__detail__description__text
                    = item.name
                  .is-content__num
                    .is-content__price
                      ¥#{item.price.to_s(:delimited, delimiter: ',')}
                    - unless item.likes.length == 0
                      %i.fa.fa-heart-o.font__gray
                        .black-inline
                          = item.likes.length
= render "layouts/breadcrumbs-bottom", item: @item

app/views/layouts/_item-show-user.html.haml
= render "layouts/breadcrumbs"
%section.dl-box
  .dl-main-all
    .dl-main-up
      %h1.dl-name
        = @item.name
      .dl-main
        .dl-photo
          .is-photo
            .is-photo__portion
              .is-photo__up
                = image_tag @item.images.first.image.url, class:"change-image"
                .is-photo__down
                  - if @item.sold_condition == 3
                    .sold-tag
                      %div SOLD

            .is-photo__down__portion
              .owl-dots
                - @images.each do |image|
                  .owl-dot
                    = image_tag image.image.url
        %table.dl-detail-table
          %tbody
            %tr.dl-tables
              %th 出品者
              %td
                = link_to "#" do
                  = @item.user.nickname
                %div
                  .dl-user-ratings
                    %i.fa.fa-laugh-squint.icon__good
                    %span 8
                  .dl-user-ratings
                    %i.fa.fa-meh.icon__normal
                    %span 1
                  .dl-user-ratings
                    %i.fa.fa-dizzy.icon__bad
                    %span 0

            %tr.dl-tables
              %th カテゴリー
              %td
                .blue-color-link
                  = link_to "/categories/#{@parent_category.id}" do
                    = @parent_category.name
                    %br
                  %i.fa.fa-chevron-right
                  = link_to "/categories/#{@child_category.id}" do
                    = @child_category.name
                    %br
                  %i.fa.fa-chevron-right
                  = link_to "/categories/#{@item.category.id}" do
                    = @item.category.name

            %tr.dl-tables
              %th ブランド
              %td
                = link_to "#" do
                  - if @item.brand.present?
                    = @item.brand.name
                  - else

            %tr.dl-tables
              %th 商品の状態
              %td
                - case @item.sold_condition
                  - when 1 then
                    新品、未使用
                  - when 2 then
                    未使用に近い
                  - when 3 then
                    目立った傷や汚れなし
                  - when 4 then
                    やや傷や汚れあり
                  - when 5 then
                    傷や汚れあり
                  - when 6 then
                    全体的に状態が悪い

            %tr.dl-tables
              %th 配送料の負担
              %td
                - case @item.delivery_payee
                  - when 1 then
                    送料込み(出品者負担)
                  - when 2 then
                    着払い(購入者負担)

            %tr.dl-tables
              %th 配送の方法
              %td
                - case @item.delivery_method
                  - when 1 then
                    未定
                  - when 2 then
                    らくらくメルカリ便
                  - when 3 then
                    ゆうメール
                  - when 4 then
                    レターパック普通郵便（定形、定形外）
                  - when 5 then
                    クロネコヤマト
                  - when 6 then
                    ゆうパック
                  - when 7 then
                    クリックポスト
                  - when 8 then
                    ゆうパケット
                  - when 9 then
                    徒歩

            %tr.dl-tables
              %th 配送元地域
              %td
                = link_to "#" do
                  = @item.region.region
            %tr.dl-tables
              %th 配送日の目安
              %td
                - case @item.delivery_time
                  - when 1 then
                    1~2日で発送
                  - when 2 then
                    2~3日で発送
                  - when 3 then
                    4~7日で発送
                  - when 4 then
                    今年中に発送
                  - when 5 then
                    発送しない

      .dl-price-box.text-center
        %span.dl-price ¥#{@item.price.to_s(:delimited, delimiter: ',')}
        %span.dl-tax (税込)
        %span.dl-shipping-fee 送料込み

      .dl-message
        %p.dl-description-inner
          =@item.description

    .dl-third-btn
      %a.dl-btn-various
        = form_with url: edit_item_path(@item), method: :get, local: true do |f|
          = f.submit "商品の編集", class: "dl-btn-various__edit"
        %p.dl-or
        = form_with url: item_path(@item), local: true, method: :delete do |f|
          = f.submit "この商品を削除する", class: "dl-btn-various__delete"

    .dl-detail-message
      = form_with url: "", method: :post, local: true, class: "dl-message-form" do |f|
        %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
        = f.text_field :comment, class: "dl-textarea-default"
        = f.submit "コメントする", class: "dl-message-submit-btn-default"

app/views/layouts/_logout.html.haml
.logout-block
  = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "next-btn btn"

app/views/layouts/_register-footer.html.haml
%footer.register-footer
  .stylebox
    %ul
      %li.stylebox__contents.stylebox__contents-margin
        = link_to "プライバシーポリシー", "#"
      %li.stylebox__contents.stylebox__contents-margin
        = link_to "メルカリ利用規約", "#"
      %li.stylebox__contents
        = link_to "特定商取引に関する表記", "#"
    = link_to "#" do
      = image_tag "footer/logo-gray.svg", size: "80x65", class: "mercari-icon"
  %p
    .bottom-text
      © 2019 Mercari

app/views/layouts/_register-header.html.haml
.logo-header
  %h1.new-user
    = link_to root_path do
      = image_tag 'header/mercari-logo.svg', size: "185x49"

app/views/layouts/_register-header6.html.haml
.logo-header__sub
  %h1.new-user
    = link_to root_path do
      = image_tag 'header/mercari-logo.svg', size: "185x49", class: "logo-clearlance"
  %nav.progress-bar
    %%ol.progress-bar-box
      %li.through
        会員情報
        .progress-status.progress-status__red
        %i.fa.fa-horizontal-rule.progress-statusbar-right.progress-statusbar-right__red
      %li.through
        電話番号認証
        .progress-status.progress-status__red
        %i.fa.fa-horizontal-rule.progress-statusbar-right.progress-statusbar-right__red
        %i.fa.fa-horizontal-rule.progress-statusbar-left.progress-statusbar-left__red
      %li.through
        お届け先住所入力
        .progress-status.progress-status__red
        %i.fa.fa-horizontal-rule.progress-statusbar-right.progress-statusbar-right__red
        %i.fa.fa-horizontal-rule.progress-statusbar-left.progress-statusbar-left__red
      %li.through
        支払い方法
        .progress-status.progress-status__red
        %i.fa.fa-horizontal-rule.progress-statusbar-right.progress-statusbar-right__red
        %i.fa.fa-horizontal-rule.progress-statusbar-left.progress-statusbar-left__red
      %li.through__red
        完了
        .progress-status.progress-status__red
        %i.fa.fa-horizontal-rule.progress-statusbar-left.progress-statusbar-left__red

app/views/layouts/_search-side-bar.html.haml
.ssb-contents
  .ssb-contents__soat
    %select{name: :sort_order, classs: "sort_order"}
      %option{value: "location.pathname", name: "location.pathname"}
        並べ替え
      %option{value: "price_asc"}
        価格の安い順
      %option{value: "price_desc"}
        価格の高い順
      %option{value: "created_at_asc"}
        出品の古い順
      %option{value: "created_at_desc"}
        出品の新しい順
  .ssb-contents__container.margin__top-40px
    .ssb-contents__box
      .sub-title
        詳細検索
      .sub-title__sub
        = fa_icon 'plus', class: "gray_icon"
        キーワードを追加する
      = search_form_for(@q, url: search_items_path) do |f|
        = f.search_field :name_cont, placeholder: "例）値下げ", class: "form-group__input"
        .ssb-contents__box
          .sub-title__sub
            = fa_icon 'list', class: "gray_icon"
            カテゴリーを選択する
        .select-wraps
          .select-wrap.iu-parent
            = f.collection_select :category_id, @parent_categories, :id, :name, {include_blank: '---'}, {id: 'parent-categories'}
            - f.collection_check_boxes :category_id_in, @parent_categories, :id, :name do |b|
              - b.check_box class: ""
        .ssb-contents__box
          .sub-title__sub
            = fa_icon 'tags', class: "gray_icon"
            ブランド名から探す
          = f.search_field :brand_name_cont, placeholder: "例）シャネル", class: "form-group__input"
        .ssb-contents__box
          .sub-title__sub
            = fa_icon 'expand', class: "gray_icon"
            サイズを指定する
          .margin__top-8px
          = f.collection_select :size_id_eq, @sizes, :id, :name, include_blank: 'すべて'
        .ssb-contents__box
          .sub-title__sub
            = fa_icon 'coins', class: "gray_icon"
            価格
          .ssb-contents__flex-box
            = f.number_field :price_gteq, placeholder: "¥ Min", class: "form-serch-price"
            = "~"
            = f.number_field :price_lteq, placeholder: "¥ Max", class: "form-serch-price"
        .ssb-contents__box
          .sub-title__sub
            = fa_icon 'star', class: "gray_icon"
            商品の状態
          .ssb-contents__box__inner
          = f.collection_check_boxes :product_condition_in, ProductCondition.all, :id, :name do |b|
            .ssb-contents__each-checkbox
              = b.check_box
              .ssb-contents__each-checkbox__label
                = b.label class: " font__size-12px"
        .ssb-contents__box
          .sub-title__sub
            = fa_icon 'truck', class: "gray_icon"
            配送料の負担
          = f.collection_check_boxes :delivery_payee_in, DeliveryPay.all, :id, :name do |b|
            .ssb-contents__each-checkbox
              = b.check_box
              .ssb-contents__each-checkbox__label
                = b.label class: "font__size-12px"
        .ssb-contents__box
          .sub-title__sub
            = fa_icon 'shopping-cart', class: "gray_icon"
            販売状況
          = f.collection_check_boxes :sold_condition_in, SalesCondition.all, :id, :name do |b|
            .ssb-contents__each-checkbox
              = b.check_box
              .ssb-contents__each-checkbox__label
                = b.label class: "font__size-12px"
          .ssb-contents__flex-box
            = link_to "クリア", "search?", class: "gray-btn"
            = f.submit "完了", class: "gray-btn red-btn"

app/views/layouts/_sell-btn.html.haml
- if user_signed_in?
  = link_to new_item_path, class: "sell-btn" do
    .sell-btn__sell 出品
    = fa_icon 'camera', class: 'sell-btn__icon-camera'

app/views/layouts/free-layout.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Mercari
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'https://fonts.googleapis.com/icon?family=Material+Icons', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield